### ISSUE TITLE
Aproveitar alguns tópicos do Project Guidelines no dev-guide

### ISSUE THREAD

**Issue by woliveiras** [luizalabs/dev-guide#10]
Galera, achei o dev-guide bem legal! :metal:  :metal:  :metal: 

Encontrei esse projeto esses dias:

https://github.com/wearehive/project-guidelines

Acham que conseguimos aproveitar alguma coisa dele e incorporar ao dev-guide?

**Comment by RomuloOliveira** [comment]
@woliveiras Que bom que gostou! É resultado de esforço colaborativo, é bom ver que mais gente se interessa.

Respondendo à pergunta: acredito que sim, dá pra aproveitar e incorporar coisas.

Eu gostei bastante da parte de [API Design](https://github.com/wearehive/project-guidelines#9-api-design-), embora tenha coisas que eu pessoalmente não concorde e que não costumamos fazer aqui. O único cuidado é de manter as coisas como guias e não como regras.

Fica à vontade pra trazer as coisas que você achar que fazem sentido pra todos, todo PR é bem vindo 😄

**Comment by eder** [comment]
👍

**Comment by RomuloOliveira** [comment]
@woliveiras tem mais alguma coisa que podemos fazer? Pode fechar essa issue? Acho que em resumo é [criar branch + PR](https://github.com/luizalabs/dev-guide/blob/master/CONTRIBUTING.md).

**Comment by woliveiras** [comment]
Opa, podemos fechar, @RomuloOliveira. :metal:
