### ISSUE TITLE
Métodos com múltiplos parâmetros não são previstos.

### ISSUE THREAD

**Issue by gabrielguaiato-luizalabs** [luizalabs/dev-guide#3]
Existem alguns casos não previstos nas guidelines de Java onde a assinatura de determinado método requer múltiplos parâmetros e a visualização pode ficar facilitada se estes forem quebrados um por linha, como no seguinte caso:

``` java
public Response method(@QueryParam("a") String paramA,
                                     @QueryParam("b") String paramB,
                                     @QueryParam("c") String paramC,
                                     @QueryParam("d") String paramD,
                                     @QueryParam("e") String paramE,
                                     @QueryParam("f") String paramF,
                                     @QueryParam("g") String paramG,
                                     @QueryParam("h") String paramH,
                                     @QueryParam("i") String paramI,
                                     @QueryParam("j") Double paramJ) throws IOException {
```

Como deveria ser formatado o método nesse caso?

**Comment by rafaelvalerini-luizalabs** [comment]
Eu gosto de usar dessa forma que você colocou no exemplo acima.. alinhando todos os parâmetros na mesma coluna. Fica mais visível quando o método tem mais de 3 ou 4 parâmetros, porém para casos onde existe de 1 até no máximo 2 ou 3 e dependendo do nome que é dados aos parâmetros(no caso de ser pequeno) prefiro na mesma linha.

**Comment by rafaelvalerini-luizalabs** [comment]
Só para completar o que falei.. No Eclipse não consegui fazer dessa forma, que eu havia falado anteriormente, para formatar automaticamente, então deixei a configuração `Wrap where Necessary`, mas sou muito a favor de deixar `Wrap all elements, except first element if not necessary`

**Comment by agrava-luizalabs** [comment]
Eu acho que temos que deixar da maneira que seja o mais legível possível, nesse caso eu prefiro utilizar também da maneira como você colocou! :+1:

**Comment by pecota-luizalabs** [comment]
@gabrielguaiato-luizalabs abre o PR ai!!! ;)
